### ISSUE TITLE
Setup on local machine need to described in details

### ISSUE THREAD

**Issue by imrrahul** [gdgnewdelhi/commudle#25]
The setup on local machine is not ellaborated in details , READ.me should contain more instructions in details

**Comment by arpansac** [comment]
Hi @imrrahul , we already have this issue, please refer to #20 
I'm soon uploading the concept of how this platform works!

**Comment by arpansac** [comment]
@imrrahul also, please do check the [How It Works](https://github.com/gdgnewdelhi/commudle/blob/master/how-it-works.md) to further understand the thinking!

**Comment by imrrahul** [comment]
Thanks @arpansac
