### ISSUE TITLE
Setting Up of the Postgres(Database).

### ISSUE THREAD

**Issue by irahulcse** [gdgnewdelhi/commudle#27]
Not able to set up the database (Postgres). There is an need for the more documentation regarding the setup of the database https://github.com/gdgnewdelhi/commudle/blob/master/project-setup.md. Just need a little bit of support regarding the setup.

**Comment by AnkushMalik** [comment]
where are you stuck?

**Comment by irahulcse** [comment]
I had been trying to set the local environment from the last day, pls take a look into #17 but right now I am not aware of how to set the postgres, as I had not worked with the Postgres earlier. The other dependencies are installed and running properly but the only database is not set up till now.

**Comment by irahulcse** [comment]
@AnkushMalik Shall I need to refer this blog for the https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-16-04 database set up. My OS==Ubuntu 18.04.

**Comment by arpansac** [comment]
@irahulcse you've found the correct link!
Please explore setting up postgres a little bit on the internet. Keeping installation instructions for a library in the project's readme seems to be less optimal to me. Also, please use Gitter for solving these doubts, I think creating an issue for this can be skipped. Closing this!

**Comment by irahulcse** [comment]
@arpansac  Thanks, Sir!
