### ISSUE TITLE
Update the setup instructions

### ISSUE THREAD

**Issue by techsethi** [gdgnewdelhi/commudle#28]
There are minor changes that needs to be done to setup instructions. I have proposed changes inline to the file. Thanks.

**Comment by techsethi** [comment]
I was getting the following error during setup
rails db:setup
1) PG::ConnectionBad: FATAL:  role "kommunity" does not exist

and then
2) -- enable_extension("uuid-ossp")
rails aborted!
ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied to create extension "uuid-ossp"
HINT:  Must be superuser to create this extension.
: CREATE EXTENSION IF NOT EXISTS "uuid-ossp

**Comment by arpansac** [comment]
Hi @techsethi ,
Thanks for pointing this out, I've changed the username for test db to gdgapp for postgres. 
The second can be simply solved by granting you postgres user, the role of superuser since we're enabling extensions. 

For suggesting more updates, please refer #20 

Thanks again!
