### ISSUE TITLE
Screen froze post registration confirmation

### ISSUE THREAD

**Issue by harshitjuneja** [gdgnewdelhi/commudle#37]
Appears like a case of Chrome blocking the UI thread.

More details:
Event: https://gdgnd.org/gcdc-new-delhi/fill-form?data_form_entity_id=36
Serverless computing on GCP.

![image](https://user-images.githubusercontent.com/11790707/53125592-63ede100-3584-11e9-9c5b-7feeb899c57b.png)

**Comment by arpansac** [comment]
@harshitjuneja , have you reproduced it on local? Actually this is the final screen after form submission, we're not taking the user anywhere from here. 
If you can elaborate a little more..

**Comment by harshitjuneja** [comment]
The behavior didn't seem intuitive since the modal didn't close as far as I remember. We can re-think UX a bit. 

It's not an issue then. The console error is from a chrome extension. 

Thanks, Closing.
